### ISSUE TITLE
Help users better understand the Results displays

### ISSUE THREAD

**Issue by serenalomonico** [shcaba/FishPath-updates#120]
Ideas include: an upfront paragraph on each of the 3 sections to orient the user; mouse-over pop-up captions to explain headings or symbols; links to short screen capture videos; also should make it explicit that you may be able to do MORE than what FishPath recommends.

**Comment by serenalomonico** [comment]
Add a legend at the top of each section of results displays to describe the symbols and colors. Provide clear guidance on the caveats (what does orange and green actually mean).

**Comment by dtdougherty** [comment]
Just flagging here the need to have short videos in place before launch

**Comment by dtdougherty** [comment]
Need video on subjective criteria in data collection section

**Comment by serenalomonico** [comment]
Edits to improve Results Page display and remove repetitive text (see following screenshot of the current results page): 
- Make the top left corner word "Results" bigger (same size as current "Options"). 
- Consider removing the word "Options" because simple the above "Results" makes more sense.

- Remove the static grey text line "Options have been plotted relative to how many positive or negative caveats are associated with them, based on properties of the fishery." This changes depending on how the user sorts/filters, so better to remove this static text. 

-Consider editing above text "These results have been calculated based upon answers to questions related to this fishery. Some options may be eliminated if they have not met certain criteria, and others will have caveats associated with them based on the feasibility or efficacy of a option given the characteristics of the fishery." to include the legend info or short info on how to filter/sort/access the narrowing process.

![image](https://user-images.githubusercontent.com/16156813/61012554-de50af00-a333-11e9-818b-c99fe04a2b17.png)

**Comment by bsnouffer** [comment]
Made a number of changes to make the UI easier to understand including:
1) Move "Generate Report" Button to the top bar since its functionality seems to fit better with the other buttons in this row. In the future, look to consolidating the all the reports into a single reporting page (and removing one of the buttons).
2) Increase the font size of the "Results" header and update the text under it. New text reads:
The interactive FishPath Tool Results display all of the individual options contained in the FishPath tool, with tailored information based on your answers to the FishPath questionnaire. The results are separated into the 3 sections of Data Collection, Assessment, and Management Measures. Some options may be eliminated if they have not met certain criteria, and others will have caveats associated with them based on the feasibility or efficacy of an option given the characteristics of the fishery. Click "Narrow Your Results" to follow a 3-step process to review, understand, and create a narrowed list of appropriate options.
3) Move "review top options" button all the way to the left, change text and background color to highlight. 
4) Make description above the results dynamic and describe the current sorting method and filters. 
5) Move show hidden toggle out of filters and sorting pop up
6) Disable toggling show hidden and enable changing sorting (as is allowed in results review) when top options only is toggled
7) Remove staring from step 1 in results review, only allow toggling hidden from step 1

All other ideas are addressed in other issues in this list so closing this one.
