### ISSUE TITLE
Ability to keep or flag options that are currently in use or not feasible with by existing policy

### ISSUE THREAD

**Issue by serenalomonico** [shcaba/FishPath-updates#124]
Somehow include the capacity to keep on the table any options that are currently in use - preferably have a separate "column" flagging that the option is currently in use (and noting the extent of confidence in this). (TBL workshop Brisbane)

Conversely, for options that may not be used, have an upfront filter to remove or flag decision rule options that are not applicable due to policy or legislative mandate.

Related to issue #123 - fishery logbooks are often eliminated due to cost, but often in use by many fisheries.

**Comment by underbluewaters** [comment]
Questions:
How would the "upfront filter" differ from hiding options in the results?

For flagging, how much do we want to tie that feature to the specific use-case of options that are currently in use? Should this be a flag that can be toggled on and off without explanation so that it can be used for multiple purposes, or should there be a tooltip or other explanation of what it means?

**Comment by underbluewaters** [comment]
On second thought, it seems like maybe a thumbs up / thumbs down icon could be useful? That could cover options that are in use *and* ones that are infeasible. We could use the comments to explain why a thumbs up/down is given for that option.

**Comment by underbluewaters** [comment]
Already addressed by new option review process
