### ISSUE TITLE
Consider adding new question: Length-weight relationships are not meaningful for some species (e.g. crabs) (QDAF workshop)

### ISSUE THREAD

**Issue by serenalomonico** [shcaba/FishPath-updates#134]
Consider adding a new question surrounding this.

**Comment by shcaba** [comment]
Instead of adding a question, could we add a caveat that says that L-W is not meaningful for some species, so any additional caveats associated with that information can be disregarded?

**Comment by bsnouffer** [comment]
There is one question regarding length-weight relationships. It is a criteria question affecting 7 assessment options and has no caveats associated with it. 

What if instead we update the question to note that length-weight isn't meaningful for all species and if it is not, then to answer No. I am making the assumption that if it is not meaningful, then one should not use a method that relies on the relationship. This puts the onus of knowing whether or not it is meaningful on the user (or workshop facilitators), but that is true no matter which of the suggestions we'd go with. Is there a reference or resource we could include that would help users determine if the relationship is meaningful?

Suggested updates in bold.

_Question_: Do you have a length-weight relationship for the species? If so, how was this obtained, and with what degree of certainty?

_Description_: This is a required input for some assessment methods. If you do not currently have an estimate of this value, the following link may provide a tool or source of information to get an estimate: www.fishbase.org 
**Length-weight relationships are not meaningful for some species, such as crabs. If it is not meaningful for this fishery, then answer 0: No, or not meaningful for this fishery**

_Answers_:
0: No, **or not meaningful for this fishery**
1: Borrowed or empirically derived
2: Measured, but with high uncertainty (e.g. low sample size, outdated data, sampling from a small area of a bigger spatial scale, or unable to differentiate gender-specific values)
3: Measured, with low to moderate uncertainty (e.g., good sample size, up to date, covers the spatial range of the species)


(for reference) Options this is a criteria for:
- SSS
- Feasible stock trajectories
- XSSS
- SCAA
- Analysis of length/size-specific catch-rate indicators for fish sampled inside and outside of marine protected areas (MPAs) or established no-take zones/reserves, and per-recruit
- YPR
- CC-SRA

**Comment by bsnouffer** [comment]
Reviewed over email, I will input into FishPath soon.

Jason: Regarding the L-W issue, can you instead use a -1 for "Not applicable", as a value of 0 should trigger a criteria issue, correct?
Is the reasoning behind combining "Not applicable" with "no data" that if a method requires L-W, maybe it is not relevant to those where L-W is not applicable? If so, I think combining them totally makes sense.

Brian: Correct, the 0 answer will trigger the criteria for those options requiring L-W.  I combined the "not meaningful for this fishery" with the "no" answer because if L-W is not meaningful, then I figured options that require L-W should be eliminated. As L-W is meaningless, then I assumed those options would not work.  I think that is what you are getting at in the 2nd line?

Jason: That is what I was getting at. What you have here sounds reasonable.

**Comment by bsnouffer** [comment]
Inputted. Closing.
