### ISSUE TITLE
Updates to report

### ISSUE THREAD

**Issue by dtdougherty** [shcaba/FishPath-updates#150]
1. Add more branding with logos, intro text referencing TNC, and with a note on each page saying "this report was generated by FishPath"

2. The options for generating a report should not include hidden options.

**Comment by dtdougherty** [comment]
Also, when generating a report, you cant navigate back and forth between the results screen and the report generation screen, so if you don't remember which was a good option, or x'd out, you have to open up a whole new browser. 

We could make it so that you can switch back and forth, or have the ability to flag in FP what the "top contenders for consideration" are and then select from that list.

**Comment by bsnouffer** [comment]
For point 2) The options that appear on the results screen are what show up in the list in the report generator. In order to not have the hidden options appear in the report generator, you need to toggle the show hidden options switch in the filters and sorting menu. I think that this is the correct behavior because if you never show the hidden options in the reporting page then there is no way to report on them without unhiding the option and it provides and easy way to remove from the reporting window by flipping the switch.

I will look into ways to allow switching between the results screen and reports generation screen.

**Comment by bsnouffer** [comment]
For the answers report, currently only the answered questions are shown. It might be useful to either show all questions, even if they don't have an answer, and/or add a number answered out of number total to each section. After a very brief look, it wasn't entirely obvious how to grab this information at the point were the report is generated.

**Comment by serenalomonico** [comment]
Passed along from Jono: In the results display or report generation - allow export as .rtf (rich text file) – doing this for FishPath would enable more readable tables for outreach purposes / reports. For instance, the “hide” and notes columns aren’t necessary and the space between Category and options could be tightened up.
Export of results tables, instead of screenshots [referring to the FishPath engagement full text reports]...
@bsnouffer - for consideration when you have a chance.

**Comment by serenalomonico** [comment]
1 - Ensure "Short List" can be checked to specifically show up in the report. Right now, you can't only select the Short List.
2 - Add a field to the field to list participant names who were in the workshop, useful to include in an Appendix

**Comment by bsnouffer** [comment]
Closing this and splitting out any remaining issues into their own threads to track easier. 

The 2 issues in the original issue have been addressed. The second comment (and Serena's 1st point) has been addressed by only showing the top options in the report pop up when only top options are shown in results.

This leaves unanswered questions in answers report, rtf and results graphic reports, and field of participant names appendix as open still.
