### ISSUE TITLE
Add short description to question "Is the life history of the species sex-specific?"

### ISSUE THREAD

**Issue by serenalomonico** [shcaba/FishPath-updates#163]
Question 3369. From Mexico workshop (Oct. 2018): Users needed clarification to understand what this means.

**Comment by NatalieDowling** [comment]
I have added the following in the description, for approval:

"Users should answer "yes" if, for example, growth rates,  maximum sizes (Linf),  or natural mortality are significantly different between males and females. 

Life-history parameters are required inputs to certain assessments, and their interpretation should be made with caution if these are sex-specific."

**Comment by dtdougherty** [comment]
Natalie, this looks good. Should we also include hermaphroditic species in your list of examples in the description? Re-tagging you for your quick comment on this.

**Comment by NatalieDowling** [comment]
Probably, yes.

**Comment by dtdougherty** [comment]
Sorry, bouncing this back again. I just realized that the question is now changed to :
"Does growth rate differ between sexes, or is age-at-maturity sex-specific?"  and does not include Natalie's description above. Does this new question suffice, or do we want to revert to old wording with description?

**Comment by NatalieDowling** [comment]
Ah, right. Good point Dawn. Thanks. So, I ummed and ahhed over the hermaphrodite thing because I was trying to think about the implications of this in terms of life history parameters. This question is really just getting at whether life-history parameters could differ by sex...

**Comment by NatalieDowling** [comment]
Just talking with Jason. 

We think we should revert to the old question, because the new one is not all-embracing, but include my originally-proposed description. 

We needn't mention hermaphrodites because, it the sex change is not simultaneously, the issues covered in the description apply anyway. If the change is simultaneous, then the life-history is not sex-specific. 

I'll make this change in FP now.

**Comment by NatalieDowling** [comment]
Changed in FP! All good so long as you guys agree.

**Comment by dtdougherty** [comment]
Sounds good, you guys are on fire today!

**Comment by dtdougherty** [comment]
I just noticed there are 2 of this same question now. One has many caveats against assessments and the other has a few green caveats against sex-regulations. I am assuming we want to remove the latter and add those caveats to the first one.

**Comment by bsnouffer** [comment]
Moving back to "in review" to make obvious we need to decide what to do with the duplicate questions. This might have come about due to the rollback Chad did to fix the loading issue. 

Both questions have the same title and description. 
_Title_: Is the life history of the species sex-specific?
_Description_: Users should answer "yes" if, for example, growth rates, maximum sizes (Linf), or natural mortality are significantly different between males and females.
Life-history parameters are required inputs to certain assessments, and their interpretation should be made with caution if these are sex-specific.

question with id 3369 has a bunch of yellow caveats against assessment methods that state "Be cautious regarding the interpretation of life-history parameters that may be sex-specific"

question with id 817 only has 3 green caveats for the sex-specific regulations that say "YES"

**Comment by dtdougherty** [comment]
Yes, I reviewed and think this looks good.

**Comment by dtdougherty** [comment]
oops, wrong one:-)

**Comment by NatalieDowling** [comment]
Hi guys, I think the questions should be merged, providing we capture the full descriptions (which I think we do, since apparently the wording is the same). Thanks.

**Comment by bsnouffer** [comment]
Looked into why there were duplicate questions and found that the question with ID 817 used to say "Does growth rate differ between sexes, or is age-at-maturity sex-specific?" (has the 3 green caveats in mgmt measures).

Looked like it was updated late Dec to have the same title and description as 3369 (which has the assessment caveats).

@NatalieDowling @shcaba I wanted to double check that the title to 817 wasn't updated by mistake and that these questions can in fact be merged.

**Comment by NatalieDowling** [comment]
I can't remember the history, but, thinking through it, I think we're okay with merging these. The new question covers everything we need. Although I think we should add "age-at-maturity is sex-specific" to the examples in the description.

**Comment by dtdougherty** [comment]
That sounds good to me.

Question 3369 should be updated to include the caveats from 817, and  now have a description that reads:
" Users should answer "yes" if, for example, growth rates, maximum sizes (Linf), age-at-maturity, or natural mortality are significantly different between males and females.
Life-history parameters are required inputs to certain assessments, and their interpretation should be made with caution if these are sex-specific."

817 will be removed when caveats are put under 3369.

**Comment by bsnouffer** [comment]
I think this makes sense as well. I will consolidate the questions.

**Comment by bsnouffer** [comment]
Updated in FishPath.
