### ISSUE TITLE
New wording for time series answer responses in assessment section

### ISSUE THREAD

**Issue by dtdougherty** [shcaba/FishPath-updates#168]
There are many questions in the assessment section asking about time series of data. Right now they are all worded the same, so we would have to go through and edit each of these manually through admin or have Chad or Brian find and replace these answer options. The below wording captures how we want to reword all answer responses for those types of questions:

Hi all,

Dawn and I are waiting for our last flight and have been looking at some assessment questions.
Here are some suggested changes to some of the data quality/quantity questions, for your consideration:
0 would remain Absent and 4 would remain "Full-time series from fishery inception" but here are suggested for 1-3
1: Snapshots/intermittent/inconsistent reporting
2: Partial time series that does not include major or peak years of catch or is missing major fleets/metiers
3: Partial time series that includes major/peak years of catches from major fleets/metiers

We added inconsistent to #1 to represent situations when some years have better reporting than others.

**Comment by dtdougherty** [comment]
can be merged with issue #109

**Comment by shcaba** [comment]
Notes from Brian and Jason:

Use above suggested changes to answers for the following questions:
What time series exists of removal data for this fishery, and at what level of usability/completeness?
What time series exists of percentile weight data (mean, median, x percentile)?
What time series exists of percentile length data (mean, median, x percentile)?
What time series exists of length composition data?
For multispecies fisheries, what time series exists of species composition data?
What time series exists of sex ratio data?
What time series exists of fishing effort data?

SURVEYS
This is a redundant question to the fishery-dependent question:
What time series exists of catch-per-unit-effort data?

For both survey types:
2: Partial time series that does not cover major or peak years of removals
3: Partial time series that cover major/peak years of removals

Change fishery-dependent wording to:
"What time series exists of fishery-dependent (e.g., catch-per-unit-effort or area) abundance data?
This refers to data collected by fishers that use their own gear and/or vessel in the absence of a scientifically designed data collection program. 


Change fishery-independent wording to:
What time series exists of fishery-independent relative or absolute abundance data?
This question refers to scientifically designed data collection programs (it does not matter who undertakes the sampling). “Relative abundance” measures only a subset of the population, and often linked to an effort or area measure. “Absolute abundance” assumes a total estimate of all animals for the assessed population (in numbers or biomass).

**Comment by shcaba** [comment]
New base answers for time series questions:

2: Time series with flaws such as missing years of major or peak catch, missing major fleets/metiers or is generally poorly sampled (i.e., high uncertainty).
3: Partial time series that includes major/peak years of catches from major fleets/metiers.

**Comment by bsnouffer** [comment]
I have updated the above questions as we listed. A few follow up questions have come up since we wrote these new answers up.

1) A new question was added: What time series exists of fishery-independent sampling inside and outside of no-take zones?" It had the old 5-10 "usable" years, 10+ "usable" years, etc. I updated it to be the answers for surveys. Jason noted though, that we might want to rethink the answers for this question as "papers have shown that you probably need to wait 10 years until you can even start sampling within the no-take."

2) We had planned on removing the CPUE question as redundant with the fishery dependent survey question. However, in the meantime the fishery dependent survey question was updated to "Is there a fishery-dependent time series, in addition to, or instead of, catch-per-unit-effort, CPUE, of relative or absolute abundance data?" However both trigger the same criteria in all cases (they are only found in "OR" criteria) making one of them redundant. Jason has proposed combining them into one question as proposed above. 
Change fishery-dependent wording to:
"What time series exists of fishery-dependent (e.g., catch-per-unit-effort or area) abundance data?
This refers to data collected by fishers that use their own gear and/or vessel in the absence of a scientifically designed data collection program.

Please respond if anyone has thoughts or opinions about these.

**Comment by bsnouffer** [comment]
Closing this as the original issue was addressed. Pulling out the 2 new issues that came up from this review into their own separate issues: #323, #324
