### ISSUE TITLE
Sort by Category not working in Data Collection section

### ISSUE THREAD

**Issue by dtdougherty** [shcaba/FishPath-updates#169]
Both "sort by category" and "sort by option name" in the sorting and filtering panel result in options be sorted by name. "Sort by category" needs to be fixed.

**Comment by bsnouffer** [comment]
This is working fine for me. Do you have anymore context about when you are experiencing the issue?

**Comment by dtdougherty** [comment]
For Jason and I, both the "sort by category" and "sort by option name" in
the sorting and filtering panel result in options be sorted by name in the
Data Collection section

**Comment by serenalomonico** [comment]
"Sort by category" is also not working in the "Results Narrowing Process" of the MM Section. We are at Step 2 "Identification of Top Options" (starring), and cannot Sort by Category (when Sort by Category is selected under Filters/Sort, it simply keeps them mixed). -Serena/Jono, Callo de Hacha fishery walk-through Dec. 17 2018.

**Comment by underbluewaters** [comment]
I can never reproduce this problem. What I think is happening is there is another, unrelated client-side error earlier in your workflow that goes unnoticed. When that happens sometimes a code-path can become "dead" because the browser doesn't want to re-trigger the error. Without that exact sequence of steps I can't trigger the sorting bug and can't fix it.

What I can do is setup a system to catch those errors in the field. I've wired up the https://sentry.io service which will report out on errors that happen in the field. It gives some pretty detailed telemetry info on the steps the user takes before the error happens that I can use to catch some of these issues more proactively.

Here's what it looks like:
<img width="1243" alt="screen shot 2019-02-04 at 9 31 31 am" src="https://user-images.githubusercontent.com/511063/52233066-3b66a700-2862-11e9-855b-fe495042211c.png">
