### ISSUE TITLE
Add orange caveat for Stochastic Stock Reduction Analysis and Question 3022

### ISSUE THREAD

**Issue by serenalomonico** [shcaba/FishPath-updates#175]
Stochastic stock reduction can’t cope with regime shifts/major management intervention/changes in price, gear, economics. There is already a static caveat for this method. Suggest adding an orange caveat against question 3022. "Has the nature of fishing operations changed, or is the nature of fishing operations changing (e.g., in terms of target species, gear types, fishing locations, or markets)?"

"I would prefer to also see this invoked as an orange caveat against the question of whether the nature of the fishery has changed." -ND.

**Comment by dtdougherty** [comment]
I propose to add an orange caveat against SSRA, when the question ""Has the nature of fishing operations changed, or is the nature of fishing operations changing (e.g., in terms of target species, gear types, fishing locations, or markets)?" has been answered Yes. The caveat will read:
This approach can’t account for regime shifts, major management interventions, or changes in price, gear, or economics. 

I will leave the static caveat in there to provide a more general caution, so that users can really think about its use in this context.
