### ISSUE TITLE
Criteria Eliminated Display Bug

### ISSUE THREAD

**Issue by bsnouffer** [shcaba/FishPath-updates#183]
An answer that eliminates the option is being shown as green in the results section. However, it correctly eliminates the option. This will cause confusion to the end users (and in this particular case is not providing the correct advise). 

I noticed this bug for the option Formal Logbooks (category: Biological Information). It lists the following for a criteria. Note that there is another answer "higher" in the hierarchy "Commercial - industrial" 
![image](https://user-images.githubusercontent.com/11687620/50785548-e1c08c00-1265-11e9-94bd-2854ba22ffe6.png)
According to the admin section, only "artisan - commercial" will satisfy the criteria and "commercial - industrial" will fail it. This is the behavior that happens in the results. An answer of "commercial - industrial" eliminates the option. However, it shows up as green in the results (under the failing criteria).

Results row:
![image](https://user-images.githubusercontent.com/11687620/50785966-05380680-1267-11e9-93f0-27d0d100b002.png)

Option Detail View:
![image](https://user-images.githubusercontent.com/11687620/50785936-f2bdcd00-1266-11e9-8e96-05f16d26f788.png)

This bug is the result of using two different logics when calculating the results and displaying the results. When calculating the results, the logic is looking for exact matches of the answer to the list in the admin section. When displaying the results, it is using an algorithm to look at the "lowest" satisfying answer and assumes everything after also satisfies. For a permanent solution, I suggest deciding on the appropriate logic and making both sections use the same (both have their own pros and cons so I won't advocate for one way right now). At a minimum, the criteria should be updated for this option and keep an eye out for this situation in other options.

**Comment by underbluewaters** [comment]
Right now it's expected that all answers that meet the criteria must be selected, so the frontend was what was inconsistent. I've updated that Criteria you listed to make "Commercial" an acceptable answer, but if I hadn't done so it would now correctly be displayed Black. I also added instructions to the options admin forms to select *all* answers.

There's a good argument for only requiring the threshold answer to be selected, and that's how the reports UI worked so it would be easy to change the results evaluation to behave that way. I'm nervous about changing the convention though since I'm not familiar with all the criteria so I took the conservative approach of just making it more consistent.
