### ISSUE TITLE
Update Ecosystem Threshold Analysis description

### ISSUE THREAD

**Issue by dtdougherty** [shcaba/FishPath-updates#185]
This needs to be more clear that it is for coral reefs.

**Comment by NatalieDowling** [comment]
I agree. But I think the only way of getting at this is (gulp) by adding a criteria question asking "Is yours a coral reef fishery?" - which we COULD possibly get at in the pre-tool survey. Thoughts?

**Comment by bsnouffer** [comment]
The current description is:
> This assessment option, specifically developed for coral reefs, uses critical reference points that have been determined for sustainable management of coral reefs. The developers of the ecosystem threshold analysis model used eight metrics of benthic cover, herbivory, predation, and diversity to reflect ecosystem state along a gradient of fishable biomass. "Threshold" values of fishable biomass were then determined, with a “threshold” being defined as "a marked change in the variance or relationship between an ecosystem driver and associated state variable" (McClanahan et al., 2011). For example, there is a marked increase in how frequently macroalgal cover dominates coral cover below a threshold of 850 kg/ha of fishable biomass. This increase may indicate a somewhat less resilient reef ecosystem. The threshold values determined by ecosystem threshold analysis can be used to guide sustainable management strategies for coral reefs in the Indian Ocean, Indonesia, and the Solomon Islands.

@NatalieDowling Two other quick changes that might highlight this more without (or in addition to) adding a new question and criteria is to (1) bold the "specifically developed for coral reefs" in the first sentence of the description or (2) update the title to something along the lines of Ecosystem Threshold Analysis (Coral Reef Fisheries Only)

**Comment by bsnouffer** [comment]
We should also consider applying whatever choice we make for this to the Ecosystem Based Biomass Targets option. Its description is:

> Ecosystem based biomass targets was developed explicitly in response to the range of difficulties that often face multispecies coral reef fisheries management. In its simplest form (McClanahan et al 2015), this method shows how coral reef fisheries could use total biomass as a reference point for management decisions. McClanahan (2018) expands on this idea to further incorporate recovery rates, changes in yields, and ecological changes to estimate sustainable yields.

**Comment by NatalieDowling** [comment]
Thanks for this, Brian. Both of these risk assessments have been kind of thorns in my side. I have circled back to the conclusion that we need to either
- add a question "Is yours a coral reef fishery?" OR
- Put in the title of the method, preferably in bold "- FOR CORAL REEF FISHERIES ONLY"

**Comment by bsnouffer** [comment]
Thinking about this more, I think ideally we should add a question for this. That matches the paradigm of the tool. These options can only be used for coral reef fisheries and therefore should be eliminated if not. It would be confusing if these options had green check marks, but then they can't be used for the fishery because its not a coral reef fishery. Also, this question should be quick to answer. Given this I am leaning towards adding the question. I am, however, concerned about adding another question that only triggers two things, but I do think as the tool currently stands, adding the question is the right way to address this.

**Comment by NatalieDowling** [comment]
I agree totally re: paradigm - hence my original suggestion. I put the other option there because of everything getting stressed about question fatigue, but I'm with you - I don't think this is a hard one. Regarding it only triggering two things, we have many questions that only trigger against a couple options. I also think the question could trigger green caveats for other risk assessments, because with coral reef fisheries you are almost certain to have to make whole-of-ecosystem concessions.

**Comment by NatalieDowling** [comment]
I agree totally re: paradigm - hence my original suggestion. I put the other option there because of everything getting stressed about question fatigue, but I'm with you - I don't think this is a hard one. Regarding it only triggering two things, we have many questions that only trigger against a couple options. I also think the question could trigger green caveats for other risk assessments, because with coral reef fisheries you are almost certain to have to make whole-of-ecosystem concessions.

**Comment by bsnouffer** [comment]
Yep Natalie, you were spot on with the original suggestion. I was holding out that we might be able to do this without a question but adding the question really makes the most sense to me as well. 

Suggesting a slight tweak to the question text: "Is _this_ a coral reef fishery?"

Answers: "Yes", "No"

No answer fails to meet criteria for the options _Ecosystem Threshold Analysis_ and _Ecosystem Based Biomass Targets_

Assigning @dtdougherty as the reviewer. @NatalieDowling  (and anyone else) feel free to add suggestions as well if desired. Once approved, I will enter the question into FishPath.

**Comment by NatalieDowling** [comment]
Yep, more than happy with this, Brian! Thanks.

**Comment by dtdougherty** [comment]
Hi Brian and Nat,

I could go either way on this one. If it is truly a criteria, meaning that you must be a coral reef fishery to do these methods, then it makes sense as a question to me. If it is something that could be used in similar fisheries outside of coral reefs, then I think putting something about how it is intended for coral reefs in title would be good. It sounds like this is a criteria, and if that is the case, then let's roll with the new criteria question.

Dawn

**Comment by bsnouffer** [comment]
My understanding of these methods and based on the discussion with @NatalieDowling above, these methods require the fishery to be a coral reef fishery. Given that, I will add the question and criteria.

**Comment by bsnouffer** [comment]
Added to FishPath.
