### ISSUE TITLE
Need formal agreement from users that their FishPath engagement allows the core group access to their answers and housed in a repository for research purposes.

### ISSUE THREAD

**Issue by shcaba** [shcaba/FishPath-updates#202]

**Comment by dtdougherty** [comment]
I think the issue around being housed in a repository should already be addressed by our current terms of use. As for the workshop context, this may need to be decided on a case by case basis. We send out the link to a subset of users depending on the situation, sometimes it is just to one person, sometimes to the group or part of it.

**Comment by dtdougherty** [comment]
Another item to consider is how users agree to the "terms of use". If a user creates an account on their own, they are agreeing to this. If we create a fishery as a group, and then email a copy, does that still apply? They will have agreed to the terms of use to open an account, so that should cover all fisheries in the account.

**Comment by underbluewaters** [comment]
On each login there is a _terms of service_ link and checkbox displayed.

<img width="941" alt="Screen Shot 2019-04-03 at 12 00 11 PM" src="https://user-images.githubusercontent.com/511063/55505516-1bf0be00-5608-11e9-862c-4d411595ce67.png">

**Comment by dtdougherty** [comment]
Okay perfect, I think that should solve any issues around that.  Thanks!
