### ISSUE TITLE
Saving issues again

### ISSUE THREAD

**Issue by dtdougherty** [shcaba/FishPath-updates#253]
In Chile, the internet (unknowingly) went out during the assessment questionnaire. No warnings were noticed, so the questionnaire was completed and notes were taken on each question, but none were saved. We had someone tracking responses so that the questionnaire could quickly be repopulated, which is our standard practice for now.

**Comment by underbluewaters** [comment]
FishPath has two ways of saving information, **background-sync** and **section-sync**.
FishPath will attempt to save each question as it is answered. This **background-sync** process, if unsuccessful, will fail and the saving indicator will likely show itself longer than usual, suggesting a timeout. Background-sync doesn't interrupt the workflow since waiting for this process to complete each question would add a long pause each time. It shouldn't be a major problem if background-sync fails since **section-sync** is more rigorous. Once a section is finished the entire questionnaire is saved again, and if this process fails the user should see this error message:

<img width="1119" alt="Screen Shot 2019-01-14 at 10 07 02 AM" src="https://user-images.githubusercontent.com/511063/58490344-d5a86e80-8121-11e9-9b52-4320c1a8aa15.png">

At that point the connection should be restored and the save step retried. There are also options to just download the data if all else fails.

I know this event was a while ago but it would be helpful to know more details about how the failure occurred. Was this save step at the end of the section reached, and if so did it show any errors like above? I can't understand how the section-sync process could have failed without indication. Is it possible that stage was not reached and only background-sync ran, failing silently in the background?

Thinking this through, it seems to me that it's an oversight that a section can be partially completed without reaching the section-sync tage. As long as the browser window isn't closed or refreshed that data should be held locally and be ready to save when the section is finished. I could add a couple more assurances:
1) Add a warning that prevents the user from closing or refreshing the browser window if there is data that hasn't been saved. They will still need to fix the internet connection before proceeding but this would prevent accidental loss of data.
2) Detect if background-sync is failing repeatedly, and if so show an indicator in the lower right corner with a manual save button. This would provide an early indicator of internet access issues, with a way to resolve it before the section is complete.

**Comment by underbluewaters** [comment]
Note for me - there are also some issues with backing out of a question without answering that should be investigated.

**Comment by underbluewaters** [comment]
I've made some extensive changes to how background-sync works. I've found some scenarios where the previous algorithm could have saved stale-changes over newer changes (which could explain losing notes), and also made the system better able to handle and retry failed saves in the case of the network going in and out. This should make the system a lot more reliable, but understandably there will still be concern about data getting lost in workshops. There's now a new status bar that you can use to monitor how FishPath is saving information, and also force saves manually.

<img width="770" alt="Screen Shot 2019-07-19 at 12 59 46 PM" src="https://user-images.githubusercontent.com/511063/61562205-a62d2880-aa25-11e9-858c-81625116fa41.png">

In the sidebar you can now enable the "Debug Tools". This setting will be remembered by your browser and is accessible to anyone. It brings up this status bar at the bottom of the screen.

<img width="495" alt="Screen Shot 2019-07-19 at 1 00 31 PM" src="https://user-images.githubusercontent.com/511063/61562264-cb219b80-aa25-11e9-88d4-43bdfbaacd8c.png">

It will show you when FishPath has pending changes, when they are being saved, and also track failures that may be due to networking or server issues.

<img width="458" alt="Screen Shot 2019-07-19 at 1 05 28 PM" src="https://user-images.githubusercontent.com/511063/61562317-ec828780-aa25-11e9-9557-c2910f12c926.png">

This interface will automatically appear, regardless of settings, if FishPath detects that it is offline or there is an error when saving an answer.

<img width="412" alt="Screen Shot 2019-07-19 at 1 06 57 PM" src="https://user-images.githubusercontent.com/511063/61562494-44b98980-aa26-11e9-9833-c3d586629465.png">

If there are outstanding changes that have not been saved it will alert the user when they attempt to navigate away from or reload the page. They can then choose to leave and lose information or stay on the page until the network is restored.

<img width="482" alt="Screen Shot 2019-07-19 at 1 07 34 PM" src="https://user-images.githubusercontent.com/511063/61562505-4a16d400-aa26-11e9-83d2-06c0d7fd8e6f.png">

While I can't foresee when it would be necessary, there is now a manual save function that will save the state of the entire questionnaire/fishery in one synchronous operation. If this succeeds you can be confident that the information has in fact saved to the FishPath database. If there is a failure or the network is not connected it will be very clear and should not fail silently.

<img width="926" alt="Screen Shot 2019-07-19 at 1 12 32 PM" src="https://user-images.githubusercontent.com/511063/61562781-f22c9d00-aa26-11e9-974b-63927b26c47e.png">

I think with these changes we will have a system that is much more ready for use in environments with poor or spotty connectivity. These changes should keep workshop organizers informed about how FishPath is performing during use and provide lots of opportunity to recovery if the internet is temporarily unavailable. Remember that if the network goes out entirely it should still be possible to finish the questionnaire, leave the browser window open (don't navigate away or refresh!), and save later. Even after putting a laptop to sleep. There could be some options for saving information even after a browser refresh or even power loss but that's an idea for another day...
