### ISSUE TITLE
Static caveat re: CPUE in assessment section

### ISSUE THREAD

**Issue by NatalieDowling** [shcaba/FishPath-updates#267]
This should not be invoked if there is no CPUE data available for the fishery. 

Instead, we perhaps should have a duality on the CPUE availability question, whereby it is both a criteria question, and, for the relevant options, where CPUE data is available, invokes the warning caveat that is currently static.

**Comment by bsnouffer** [comment]
Static caveats regarding CPUE and the criteria group CPUE is in for each option. 

Large multis have 9 or 10 time series that could satisfy criteria. Fishery ind/dep multi has the following 3 questions that could satisfy: fishery independent relative or absolute abundance, CPUE time series, or fishery dependent other than CPUE time series.

- Use CPUE with extreme caution, consult local experts to understand degree to which technology or catchability may have changed over time.
  - **CUSUM** - CPUE part of large multi criteria
  - **Data exploration via plotting and descriptive statistics** - CPUE part of large multi
  - **Depletion analysis** - CPUE part of fishery ind/dep multi
  - **Hierarchical decision trees** - CPUE part of large multi
  - **Linear regression to recent time series of CPUE** - CPUE part of fishery ind/dep multi
  - **Production Model** - part of fishery ind/dep multi
  - **Sequential trigger framework involving catch and/or effort, CPUE, size, sex ratio etc.** - CPUE part of large multi
  - **Single-indicator analysis using standardized CPUE** - part of fishery ind/dep multi
  - **SCAA** - part of fishery ind/dep multi
  - **SAFE** - part of fishery ind/dep + effort + removals multi
  - **Traffic Lights** - part of large multi
	
- For this method, if CPUE is used as a biomass proxy, it is typically as a snapshot rather than a time series. However, CPUE should generally be used with extreme caution, consult local experts to understand degree to which technology or catchability may have changed over time.
  - **Use of biomass surveys to inform spatial management** - part of fishery ind/dep multi

**Comment by bsnouffer** [comment]
This should be reviewed at the same time as #324 (proposing to combine the CPUE and fishery dependent questions)

**Comment by bsnouffer** [comment]
Assigning Jono to review with his review of 324. One decision to be made is the color of the caveat, I am leaning towards yellow as this is something to be conscious and wary of when utilizing and interpreting the data, not something that is a deal breaker. Given that the wording is "use extreme caution" I could maybe see this being an orange if we really wanted it to stand out from the crowd.

**Comment by jonowilson** [comment]
wondering if we should also encourage a standardization process, and/or include other elements to consider beyond technology change and catchability? e.g. we could say, " Use CPUE with extreme caution, consult local experts to understand degree to which technology or catchability may have changed over space and time, and if possible standardize the values using best practices.

**Comment by jonowilson** [comment]
i think use of CPUE needs to be a very thoughtful and rigorous process and should therefore be orange...

**Comment by NatalieDowling** [comment]
Agree re: orange!

**Comment by NatalieDowling** [comment]
And yes, I like Jono's suggestion of wording to encourage standardisation.

**Comment by bsnouffer** [comment]
Inputted into FishPath
