### ISSUE TITLE
FishPath Tool Dashboard Updates

### ISSUE THREAD

**Issue by bsnouffer** [shcaba/FishPath-updates#301]
1. Move user guide to its own section just below the text to call it out more
2. Change the number of fisheries shown per page to 5
3. Review the text and update as needed
4. Update the user guide link once it is live
5. Remove scroll bar from reference materials section

![image](https://user-images.githubusercontent.com/11687620/70266166-d402d780-1750-11ea-976a-086103b4cd19.png)

**Comment by serenalomonico** [comment]
@bsnouffer  - I addressed these and added a few new ones:

1. Move user guide to its own section just below the text to call it out more.
Add a new, first heading "FishPath Tool User Guide" in the same font/size as other headings. 
**FishPath Tool User Guide**
The FishPath Tool User Guide (hyperlink) contains detail on using the FishPath Tool and interpreting results.

2. Change the number of fisheries shown per page to 5.

3. Review the text and update as needed. **Revised intro text:**
"Welcome to your FishPath Tool Dashboard. Here, you may view the "FishPath Tool User Guide". Your existing FishPath tool fishery questionnaires and results are found under "My Fisheries". New fisheries may be added using the "Add a Fishery" button. Below, you may access the full list of options and resources contained within the FishPath tool under "Reference Materials". You may also access these same materials through the top left menu."

4. Update the user guide link once it is live. (See Point 1). 

5. Remove scroll bar from reference materials section. 
**Also** change the tag line on the "Reference Materials" heading as: 
Options within the FishPath tool are divided into the 3 sections below. 

6. Update the Top Left Blue Menu. Change to "FishPath Tool" instead of "FishPath".
When /// clicked, the headings should be in vertical order of:
[User Name]
Sign Out
------horizontal bar------
FishPath Tool User Guide
My Fisheries
Reference Materials
(remove "Contact Us") the "Help Us Improve.." heading is sufficient. 
Keep "Admin" & "Debug Tools" as is

7. The final "Help Us Improve.." heading (capitalize the **T in tool**) has a weird space after it and before the tag line. Put the tag line in the same grey style as Ref Materials tag line to remove space.

**Comment by dtdougherty** [comment]
This looks good to me, will leave for Brian's review.

**Comment by bsnouffer** [comment]
Waiting to include the link to the user guide until that is ready for launch. Otherwise completed, so closing. mcclintock-lab/FishPath#60
