### ISSUE TITLE
Bookmark & Notes Flags

### ISSUE THREAD

**Issue by serenalomonico** [shcaba/FishPath-updates#321]
In Flagged Questions section, it’s difficult to tell a difference between questions that have both a bookmark  (green flag) and notes (yellow flag). For example, if I want to see all the green bookmarked questions, the yellow ones denote that there’s a note, but you can’t tell without clicking whether it also has a green book mark. For a solution, consider 2 separate icons side by side. Green flag is a bookmark & a new yellow “Note” icon if there is also a note.

**Comment by bsnouffer** [comment]
Updated to show icons signifying both if the question has been bookmarked and a note is taken. Also updated the notes to use the same icon signifying a note in the results section instead of the orange ribbon for consistency. Finally added a note icon to the bookmark and influential answers sections in results if the questions have a note.

Completed in mcclintock-lab/FishPath#70
