### ISSUE TITLE
"Full" time series are never available

### ISSUE THREAD

**Issue by shcaba** [shcaba/FishPath-updates#358]
Andre pointed out that no one ever really has a full time series, which is totally fair.
My suggestion is to change the answer "Full time series since fishing began" to "Time series since fishing began or assuming all remaining historical removals are small to negligible".

**Comment by bsnouffer** [comment]
All the data time series questions ("What time series exists of...") include "Full time series since fishing began":

1. species composition (220)
2. length composition (227)
3. percentile length (239)
4. percentile weight (245)
5. removals (251)
6. fishing effort (257)
7. opportunistic abundance indices (fishery-dependent) (263)
8. sex ratios (269)
9. scientifically designed surveys of relative abundance (fishery-independent) (281)
10. fishery independent sampling inside and outside no-take zones (287)

**Comment by bsnouffer** [comment]
I will update the answer as Jason suggests next week, unless there is objection.

**Comment by NatalieDowling** [comment]
Sounds great to me. Thanks, Jason and Brian.

**Comment by bsnouffer** [comment]
The time series answers are being updated and tracked in #382. This is a more detailed overhaul than listed above:

> New 4: Flaws in time series data representativeness and sampling levels are minimal, and bias and imprecision are not a major concern. Examples are time series that cover the full extent of the known fishing history, fleets and areas, as well as high resolution in species reporting and sufficient sample sizes to minimize imprecision.
_(slight tweaks for some of the questions)_

Jason noted that this is still a pretty high bar, and very few fisheries would likely meet this requirement, even in data rich fisheries. However, this is not an issue, as the point is to highlight that users need to confront and address any bias or imprecision in the time series. Fisheries should work to continue addressing areas of bias and imprecision and work on continuing to reduce them in the data collection program moving forward.

**Comment by NatalieDowling** [comment]
Hi Brian and Jason,

Just reviewing all Brian’s emails since the start of the month, and acknowledging changes.

Wanted to say that this is a terrific amendment and one that is already making a difference – thank you.

Natalie
