### ISSUE TITLE
Add New Question regarding whether certain options are legislative requirements

### ISSUE THREAD

**Issue by serenalomonico** [shcaba/FishPath-updates#68]
Add a criteria question on whether certain options are legislative requirements (e.g. TEPS monitoring).
From Natalie (Darwin workshop)

**Comment by bsnouffer** [comment]
Not sure how this could feasibly be implemented without being a mess, but am open to suggestions. There is now guidance in the results review for monitoring and management measures to remove options that are inconsistent with legislation. If this is still desired, it might be worth looking at the guidance in the narrowing process instead of a question, but I am open to other ideas.

**Comment by bsnouffer** [comment]
From #181:

> Address higher level requirements, such as around HCRs, or identify broader requirements that equate to fixed management measures (such as rulings on gear restrictions). I’m not sure that this translates across to developing nations. Suggest we add a question about whether there are higher-level gear, spatial, or other requirements (e.g. manage by TACs), and, according to responses, flag those measures that are required by law or policy as green caveats. - ND

**Comment by bsnouffer** [comment]
Discussed on a call with Natalie and Jason. Beyond the logistical issues mentioned above, legislation requirements does not make an option any better or worse situated for the fishery. This is more suited as advice within the results narrowing process and is already mentioned in the results narrowing instructions.
