### ISSUE TITLE
Influential answers totals

### ISSUE THREAD

**Issue by shcaba** [shcaba/FishPath-updates#85]
The numbers is the circles do not add up to the number given ("This answer impacts N options") when you click on the answer to the question. Should they be the same?

**Comment by underbluewaters** [comment]
What was happening was the modals were showing only caveats for the given section, while the influential answers list was showing caveat counts for all sections. I updated the bubble display to only show those for the current section.

Note that there may still be some inconsistency. The bubble chart doesn't display green caveats since those aren't considered in the influence calculation. So the modal may display a higher count if there are green caveats.
