### ISSUE TITLE
Users should be able to report errors or new content ideas, etc.

### ISSUE THREAD

**Issue by dtdougherty** [shcaba/FishPath-updates#89]
Perhaps they can add comments that add to our github list or we approve and add, something like that

**Comment by serenalomonico** [comment]
There should be a button or area for users to suggest new questions or provide comments on how FishPath should be enhanced to incorporate new caveats, considerations, or expand on current.

**Comment by underbluewaters** [comment]
There are a few different ways to go about this.

The simplest way is by email. I could put a feedback button in the app which opens a form where users submit comments that end up being sent to support@fishpath.org. We could have some sort of template that asks for feedback in a particular form in this case. That would take me a couple hours to put together. We could potentially link to github from that window for the adventurous users.

The more complex way is by using a service like [Intercom](https://www.intercom.com/customer-support-software) or UserVoice. These are pretty easy to integrate into an app but require a lot of work to get value out of them. They can be used to author a whole set of support articles and documentation that users will be guided to when they ask questions. Some of these tools support adding and voting on feature requests. They all help a team manage support requests. It's a pretty crowded space so I'm not sure what would be a good offering. Many of the best options are into the hundreds of dollars a month because they are targeting tech startups.

**Comment by underbluewaters** [comment]
Dropdown options for contact form.
[new caveat]
[new options]
[new question]
[general comments]
